### ISSUE TITLE
Use gom for dependency mangement

### ISSUE THREAD

**Issue by tsheasha** [bobtfish/AWSnycast#14]
Using this tool is easier than godep, so let's give it a try

**Comment by tsheasha** [comment]
I am about to push a patch for this, in this patch I will also restructure the code to make it more with the go convention of structuring code. 

This will allow me to edit the Makefile in a way to make running the make command much easier. I have been struggling for a while to run tests locally, hopefully with this change this will no longer be the case for myself or any of the future contributors.

**Comment by bobtfish** [comment]
Sounds good!

**Comment by bobtfish** [comment]
@tsheasha I intend to merge PR #16 as soon as I get Travis green, legit?

**Comment by tsheasha** [comment]
lgtm! ship it

**Comment by bobtfish** [comment]
Shipped!
